name: ppotto-dev

services:
  caddy:
    env_file:
      - .env.dev

  app:
    image: ${APP_IMAGE:-ppotto-server:dev}
    env_file:
      - .env.dev
    volumes:
      - ../secrets/gcs-dev-service-account.json:/run/secrets/gcs-service-account.json:ro,z

  postgres:
    env_file:
      - .env.dev
    mem_limit: 2g
