name: ppotto-production

services:
  caddy:
    env_file:
      - .env.production

  app:
    image: ${APP_IMAGE:-ppotto-server:production}
    env_file:
      - .env.production
    volumes:
      - ../secrets/gcs-production-service-account.json:/run/secrets/gcs-service-account.json:ro,z

  postgres:
    env_file:
      - .env.production
    mem_limit: 3g

  valkey:
    env_file:
      - .env.production
