sentry:
  dsn: ${SENTRY_DSN}
  environment: ${SENTRY_ENVIRONMENT}
  traces-sample-rate: ${SENTRY_TRACES_SAMPLE_RATE}
  send-default-pii: true
  max-request-body-size: always
  logging:
    enabled: true
    minimum-event-level: error
    minimum-breadcrumb-level: info
