server:
  port: ${SERVER_PORT}
  shutdown: graceful

spring:
  threads:
    virtual:
      enabled: true
  lifecycle:
    timeout-per-shutdown-phase: 20s

---
spring:
  config:
    activate:
      on-profile: prod

server:
  forward-headers-strategy: framework
