springdoc:
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
    persist-authorization: true
